version: '3'

services:
  web:
    image: nginx:latest
    volumes:
      - ../web:/usr/share/nginx/html
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../data:/usr/share/nginx/data
    ports:
      - "8011:80"
    depends_on:
      - api

  api:
    build: ../api
    volumes:
      - ../data:/data
    environment:
      - API_KEY=app-5DJwE74ZkYcbteeUm9xQ7HiK # 测试用
      # - API_KEY=app-RPbXiETBBDhaYT4ab5WQnwFs # 生产用
      - WORKFLOW_HOST = http://192.168.0.103 # 内网用
      # - WORKFLOW_HOST = http://863deprd.tpddns.cn # 公网用